/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActividadesRouteImport } from './routes/actividades'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as DispositivosRouteImport } from './routes/dispositivos'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as MasRouteImport } from './routes/mas'
import { Route as NotificacionesRouteImport } from './routes/notificaciones'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as PuntosRouteImport } from './routes/puntos'
import { Route as RegistrarRouteImport } from './routes/registrar'
import { Route as RetosRouteImport } from './routes/retos'
import { Route as MasIndexRouteImport } from './routes/mas.index'
import { Route as MasAyudaRouteImport } from './routes/mas.ayuda'
import { Route as MasConfiguracionRouteImport } from './routes/mas.configuracion'
import { Route as MasEntrenamientoRouteImport } from './routes/mas.entrenamiento'
import { Route as MasPerfilRouteImport } from './routes/mas.perfil'
import { Route as MasRendimientoRouteImport } from './routes/mas.rendimiento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadesRoute = ActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const DispositivosRoute = DispositivosRouteImport.update({
  id: '/dispositivos',
  path: '/dispositivos',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const MasRoute = MasRouteImport.update({
  id: '/mas',
  path: '/mas',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacionesRoute = NotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const PuntosRoute = PuntosRouteImport.update({
  id: '/puntos',
  path: '/puntos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarRoute = RegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const RetosRoute = RetosRouteImport.update({
  id: '/retos',
  path: '/retos',
  getParentRoute: () => rootRouteImport,
} as any)
const MasIndexRoute = MasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MasRoute,
} as any)
const MasAyudaRoute = MasAyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => MasRoute,
} as any)
const MasConfiguracionRoute = MasConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => MasRoute,
} as any)
const MasEntrenamientoRoute = MasEntrenamientoRouteImport.update({
  id: '/entrenamiento',
  path: '/entrenamiento',
  getParentRoute: () => MasRoute,
} as any)
const MasPerfilRoute = MasPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => MasRoute,
} as any)
const MasRendimientoRoute = MasRendimientoRouteImport.update({
  id: '/rendimiento',
  path: '/rendimiento',
  getParentRoute: () => MasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/calendario': typeof CalendarioRoute
  '/dispositivos': typeof DispositivosRoute
  '/equipo': typeof EquipoRoute
  '/mas': typeof MasRouteWithChildren
  '/notificaciones': typeof NotificacionesRoute
  '/planes': typeof PlanesRoute
  '/puntos': typeof PuntosRoute
  '/registrar': typeof RegistrarRoute
  '/retos': typeof RetosRoute
  '/mas/ayuda': typeof MasAyudaRoute
  '/mas/configuracion': typeof MasConfiguracionRoute
  '/mas/entrenamiento': typeof MasEntrenamientoRoute
  '/mas/perfil': typeof MasPerfilRoute
  '/mas/rendimiento': typeof MasRendimientoRoute
  '/mas/': typeof MasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/calendario': typeof CalendarioRoute
  '/dispositivos': typeof DispositivosRoute
  '/equipo': typeof EquipoRoute
  '/notificaciones': typeof NotificacionesRoute
  '/planes': typeof PlanesRoute
  '/puntos': typeof PuntosRoute
  '/registrar': typeof RegistrarRoute
  '/retos': typeof RetosRoute
  '/mas/ayuda': typeof MasAyudaRoute
  '/mas/configuracion': typeof MasConfiguracionRoute
  '/mas/entrenamiento': typeof MasEntrenamientoRoute
  '/mas/perfil': typeof MasPerfilRoute
  '/mas/rendimiento': typeof MasRendimientoRoute
  '/mas': typeof MasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/calendario': typeof CalendarioRoute
  '/dispositivos': typeof DispositivosRoute
  '/equipo': typeof EquipoRoute
  '/mas': typeof MasRouteWithChildren
  '/notificaciones': typeof NotificacionesRoute
  '/planes': typeof PlanesRoute
  '/puntos': typeof PuntosRoute
  '/registrar': typeof RegistrarRoute
  '/retos': typeof RetosRoute
  '/mas/ayuda': typeof MasAyudaRoute
  '/mas/configuracion': typeof MasConfiguracionRoute
  '/mas/entrenamiento': typeof MasEntrenamientoRoute
  '/mas/perfil': typeof MasPerfilRoute
  '/mas/rendimiento': typeof MasRendimientoRoute
  '/mas/': typeof MasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actividades'
    | '/calendario'
    | '/dispositivos'
    | '/equipo'
    | '/mas'
    | '/notificaciones'
    | '/planes'
    | '/puntos'
    | '/registrar'
    | '/retos'
    | '/mas/ayuda'
    | '/mas/configuracion'
    | '/mas/entrenamiento'
    | '/mas/perfil'
    | '/mas/rendimiento'
    | '/mas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actividades'
    | '/calendario'
    | '/dispositivos'
    | '/equipo'
    | '/notificaciones'
    | '/planes'
    | '/puntos'
    | '/registrar'
    | '/retos'
    | '/mas/ayuda'
    | '/mas/configuracion'
    | '/mas/entrenamiento'
    | '/mas/perfil'
    | '/mas/rendimiento'
    | '/mas'
  id:
    | '__root__'
    | '/'
    | '/actividades'
    | '/calendario'
    | '/dispositivos'
    | '/equipo'
    | '/mas'
    | '/notificaciones'
    | '/planes'
    | '/puntos'
    | '/registrar'
    | '/retos'
    | '/mas/ayuda'
    | '/mas/configuracion'
    | '/mas/entrenamiento'
    | '/mas/perfil'
    | '/mas/rendimiento'
    | '/mas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActividadesRoute: typeof ActividadesRoute
  CalendarioRoute: typeof CalendarioRoute
  DispositivosRoute: typeof DispositivosRoute
  EquipoRoute: typeof EquipoRoute
  MasRoute: typeof MasRouteWithChildren
  NotificacionesRoute: typeof NotificacionesRoute
  PlanesRoute: typeof PlanesRoute
  PuntosRoute: typeof PuntosRoute
  RegistrarRoute: typeof RegistrarRoute
  RetosRoute: typeof RetosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividades': {
      id: '/actividades'
      path: '/actividades'
      fullPath: '/actividades'
      preLoaderRoute: typeof ActividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispositivos': {
      id: '/dispositivos'
      path: '/dispositivos'
      fullPath: '/dispositivos'
      preLoaderRoute: typeof DispositivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mas': {
      id: '/mas'
      path: '/mas'
      fullPath: '/mas'
      preLoaderRoute: typeof MasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificaciones': {
      id: '/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof NotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puntos': {
      id: '/puntos'
      path: '/puntos'
      fullPath: '/puntos'
      preLoaderRoute: typeof PuntosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar': {
      id: '/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof RegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retos': {
      id: '/retos'
      path: '/retos'
      fullPath: '/retos'
      preLoaderRoute: typeof RetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mas/': {
      id: '/mas/'
      path: '/'
      fullPath: '/mas/'
      preLoaderRoute: typeof MasIndexRouteImport
      parentRoute: typeof MasRoute
    }
    '/mas/ayuda': {
      id: '/mas/ayuda'
      path: '/ayuda'
      fullPath: '/mas/ayuda'
      preLoaderRoute: typeof MasAyudaRouteImport
      parentRoute: typeof MasRoute
    }
    '/mas/configuracion': {
      id: '/mas/configuracion'
      path: '/configuracion'
      fullPath: '/mas/configuracion'
      preLoaderRoute: typeof MasConfiguracionRouteImport
      parentRoute: typeof MasRoute
    }
    '/mas/entrenamiento': {
      id: '/mas/entrenamiento'
      path: '/entrenamiento'
      fullPath: '/mas/entrenamiento'
      preLoaderRoute: typeof MasEntrenamientoRouteImport
      parentRoute: typeof MasRoute
    }
    '/mas/perfil': {
      id: '/mas/perfil'
      path: '/perfil'
      fullPath: '/mas/perfil'
      preLoaderRoute: typeof MasPerfilRouteImport
      parentRoute: typeof MasRoute
    }
    '/mas/rendimiento': {
      id: '/mas/rendimiento'
      path: '/rendimiento'
      fullPath: '/mas/rendimiento'
      preLoaderRoute: typeof MasRendimientoRouteImport
      parentRoute: typeof MasRoute
    }
  }
}

interface MasRouteChildren {
  MasAyudaRoute: typeof MasAyudaRoute
  MasConfiguracionRoute: typeof MasConfiguracionRoute
  MasEntrenamientoRoute: typeof MasEntrenamientoRoute
  MasPerfilRoute: typeof MasPerfilRoute
  MasRendimientoRoute: typeof MasRendimientoRoute
  MasIndexRoute: typeof MasIndexRoute
}

const MasRouteChildren: MasRouteChildren = {
  MasAyudaRoute: MasAyudaRoute,
  MasConfiguracionRoute: MasConfiguracionRoute,
  MasEntrenamientoRoute: MasEntrenamientoRoute,
  MasPerfilRoute: MasPerfilRoute,
  MasRendimientoRoute: MasRendimientoRoute,
  MasIndexRoute: MasIndexRoute,
}

const MasRouteWithChildren = MasRoute._addFileChildren(MasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActividadesRoute: ActividadesRoute,
  CalendarioRoute: CalendarioRoute,
  DispositivosRoute: DispositivosRoute,
  EquipoRoute: EquipoRoute,
  MasRoute: MasRouteWithChildren,
  NotificacionesRoute: NotificacionesRoute,
  PlanesRoute: PlanesRoute,
  PuntosRoute: PuntosRoute,
  RegistrarRoute: RegistrarRoute,
  RetosRoute: RetosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
