/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DispositivosRouteImport } from './routes/dispositivos'
import { Route as MasRouteImport } from './routes/mas'
import { Route as MasAyudaRouteImport } from './routes/mas.ayuda'
import { Route as MasConfiguracionRouteImport } from './routes/mas.configuracion'
import { Route as MasEntrenamientoRouteImport } from './routes/mas.entrenamiento'
import { Route as MasPerfilRouteImport } from './routes/mas.perfil'
import { Route as MasRendimientoRouteImport } from './routes/mas.rendimiento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DispositivosRoute = DispositivosRouteImport.update({
  id: '/dispositivos',
  path: '/dispositivos',
  getParentRoute: () => rootRouteImport,
} as any)
const MasRoute = MasRouteImport.update({
  id: '/mas',
  path: '/mas',
  getParentRoute: () => rootRouteImport,
} as any)
const MasAyudaRoute = MasAyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => MasRoute,
} as any)
const MasConfiguracionRoute = MasConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => MasRoute,
} as any)
const MasEntrenamientoRoute = MasEntrenamientoRouteImport.update({
  id: '/entrenamiento',
  path: '/entrenamiento',
  getParentRoute: () => MasRoute,
} as any)
const MasPerfilRoute = MasPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => MasRoute,
} as any)
const MasRendimientoRoute = MasRendimientoRouteImport.update({
  id: '/rendimiento',
  path: '/rendimiento',
  getParentRoute: () => MasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dispositivos': typeof DispositivosRoute
  '/mas': typeof MasRouteWithChildren
  '/mas/ayuda': typeof MasAyudaRoute
  '/mas/configuracion': typeof MasConfiguracionRoute
  '/mas/entrenamiento': typeof MasEntrenamientoRoute
  '/mas/perfil': typeof MasPerfilRoute
  '/mas/rendimiento': typeof MasRendimientoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dispositivos': typeof DispositivosRoute
  '/mas': typeof MasRouteWithChildren
  '/mas/ayuda': typeof MasAyudaRoute
  '/mas/configuracion': typeof MasConfiguracionRoute
  '/mas/entrenamiento': typeof MasEntrenamientoRoute
  '/mas/perfil': typeof MasPerfilRoute
  '/mas/rendimiento': typeof MasRendimientoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dispositivos': typeof DispositivosRoute
  '/mas': typeof MasRouteWithChildren
  '/mas/ayuda': typeof MasAyudaRoute
  '/mas/configuracion': typeof MasConfiguracionRoute
  '/mas/entrenamiento': typeof MasEntrenamientoRoute
  '/mas/perfil': typeof MasPerfilRoute
  '/mas/rendimiento': typeof MasRendimientoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dispositivos'
    | '/mas'
    | '/mas/ayuda'
    | '/mas/configuracion'
    | '/mas/entrenamiento'
    | '/mas/perfil'
    | '/mas/rendimiento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dispositivos'
    | '/mas'
    | '/mas/ayuda'
    | '/mas/configuracion'
    | '/mas/entrenamiento'
    | '/mas/perfil'
    | '/mas/rendimiento'
  id:
    | '__root__'
    | '/'
    | '/dispositivos'
    | '/mas'
    | '/mas/ayuda'
    | '/mas/configuracion'
    | '/mas/entrenamiento'
    | '/mas/perfil'
    | '/mas/rendimiento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DispositivosRoute: typeof DispositivosRoute
  MasRoute: typeof MasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispositivos': {
      id: '/dispositivos'
      path: '/dispositivos'
      fullPath: '/dispositivos'
      preLoaderRoute: typeof DispositivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mas': {
      id: '/mas'
      path: '/mas'
      fullPath: '/mas'
      preLoaderRoute: typeof MasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mas/ayuda': {
      id: '/mas/ayuda'
      path: '/ayuda'
      fullPath: '/mas/ayuda'
      preLoaderRoute: typeof MasAyudaRouteImport
      parentRoute: typeof MasRoute
    }
    '/mas/configuracion': {
      id: '/mas/configuracion'
      path: '/configuracion'
      fullPath: '/mas/configuracion'
      preLoaderRoute: typeof MasConfiguracionRouteImport
      parentRoute: typeof MasRoute
    }
    '/mas/entrenamiento': {
      id: '/mas/entrenamiento'
      path: '/entrenamiento'
      fullPath: '/mas/entrenamiento'
      preLoaderRoute: typeof MasEntrenamientoRouteImport
      parentRoute: typeof MasRoute
    }
    '/mas/perfil': {
      id: '/mas/perfil'
      path: '/perfil'
      fullPath: '/mas/perfil'
      preLoaderRoute: typeof MasPerfilRouteImport
      parentRoute: typeof MasRoute
    }
    '/mas/rendimiento': {
      id: '/mas/rendimiento'
      path: '/rendimiento'
      fullPath: '/mas/rendimiento'
      preLoaderRoute: typeof MasRendimientoRouteImport
      parentRoute: typeof MasRoute
    }
  }
}

interface MasRouteChildren {
  MasAyudaRoute: typeof MasAyudaRoute
  MasConfiguracionRoute: typeof MasConfiguracionRoute
  MasEntrenamientoRoute: typeof MasEntrenamientoRoute
  MasPerfilRoute: typeof MasPerfilRoute
  MasRendimientoRoute: typeof MasRendimientoRoute
}

const MasRouteChildren: MasRouteChildren = {
  MasAyudaRoute: MasAyudaRoute,
  MasConfiguracionRoute: MasConfiguracionRoute,
  MasEntrenamientoRoute: MasEntrenamientoRoute,
  MasPerfilRoute: MasPerfilRoute,
  MasRendimientoRoute: MasRendimientoRoute,
}

const MasRouteWithChildren = MasRoute._addFileChildren(MasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DispositivosRoute: DispositivosRoute,
  MasRoute: MasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
